require "json"
require "yaml"
require "uri"

require "./amber_lsp/version"
require "./amber_lsp/rules/severity"
require "./amber_lsp/rules/diagnostic"
require "./amber_lsp/rules/base_rule"
require "./amber_lsp/rules/rule_registry"
require "./amber_lsp/rules/controllers/*"
require "./amber_lsp/rules/jobs/*"
require "./amber_lsp/rules/channels/*"
require "./amber_lsp/rules/pipes/*"
require "./amber_lsp/rules/mailers/*"
require "./amber_lsp/rules/schemas/*"
require "./amber_lsp/rules/file_naming/*"
require "./amber_lsp/rules/routing/*"
require "./amber_lsp/rules/specs/*"
require "./amber_lsp/rules/sockets/*"
require "./amber_lsp/document_store"
require "./amber_lsp/project_context"
require "./amber_lsp/configuration"
require "./amber_lsp/analyzer"
require "./amber_lsp/controller"
require "./amber_lsp/server"

AmberLSP::Server.new(STDIN, STDOUT).run
