require "./capability_manifest"

module AmberCLI::Native
  class AppleShellGenerator
    APP_SHORTCUT_APP_NAME_PLACEHOLDER = "__AMBER_APP_SHORTCUT_APPLICATION_NAME__"
    GENERATED_HEADER = <<-HEADER
// This file is Generated by amber_cli from config/native.yml.
// Safe to regenerate: edit config/native.yml or mobile/ios/Sources/**/* instead.

HEADER

    getter manifest : CapabilityManifest
    getter app_name : String
    getter pascal_name : String

    def initialize(@manifest : CapabilityManifest, @app_name : String)
      @pascal_name = Naming.pascalize(app_name)
    end

    def write(project_path : String) : Nil
      write_file(project_path, "config/native.yml", @manifest.to_yaml_document)
      write_file(project_path, "mobile/apple/generated/README.md", ownership_readme)
      write_file(project_path, "mobile/apple/generated/WidgetKit/WidgetKitScaffold.swift", GENERATED_HEADER + widgets_catalog.export_widgetkit_scaffold)
      write_file(project_path, "mobile/apple/generated/WidgetKit/#{pascal_name}WidgetBundle.swift", widget_bundle_wrapper)
      write_file(project_path, "mobile/apple/generated/WidgetKit/Info.plist", widget_extension_info_plist)
      write_file(project_path, "mobile/apple/generated/ActivityKit/ActivityKitScaffold.swift", GENERATED_HEADER + live_activities_catalog.export_activitykit_scaffold)
      write_file(project_path, "mobile/apple/generated/ActivityKit/#{pascal_name}LiveActivityWidgets.swift", live_activity_widget_wrapper)
      write_file(project_path, "mobile/apple/generated/AppIntents/AppIntentsScaffold.swift", GENERATED_HEADER + shortcuts_catalog.export_app_intents_scaffold)
      write_file(project_path, "mobile/apple/generated/AppIntents/#{pascal_name}AppShortcutsProvider.swift", app_shortcuts_provider)
      write_file(project_path, "mobile/apple/generated/Notifications/NotificationsScaffold.swift", GENERATED_HEADER + notifications_catalog.export_swift_scaffold)
      write_file(project_path, "mobile/apple/generated/Notifications/#{pascal_name}NotificationsBootstrap.swift", notifications_bootstrap)
      write_file(project_path, "mobile/apple/generated/QuickActions/UIApplicationShortcutItems.plist.fragment", quick_actions_fragment)
      write_file(project_path, "mobile/ios/Sources/#{pascal_name}App.swift", ios_app_source)
      write_file(project_path, "mobile/ios/Sources/#{pascal_name}AppDelegate.swift", ios_app_delegate_source)
      write_file(project_path, "mobile/ios/Sources/ContentView.swift", ios_content_view_source)
    end

    def ios_project_yml : String
      <<-YML
name: #{pascal_name}
options:
  deploymentTarget:
    iOS: "#{@manifest.apple.minimum_ios_version}"
settings:
  # CRITICAL: Crystal only compiles arm64. Exclude x86_64 from simulator builds.
  EXCLUDED_ARCHS[sdk=iphonesimulator*]: x86_64
targets:
  #{pascal_name}:
    type: application
    platform: iOS
    sources:
      - path: Sources
      - path: ../apple/generated/AppIntents
      - path: ../apple/generated/Notifications
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: #{@manifest.apple.bundle_identifier}
      GENERATE_INFOPLIST_FILE: YES
      LIBRARY_SEARCH_PATHS: $(PROJECT_DIR)/build
      OTHER_LDFLAGS:
        - -l#{app_name}
        - -lgc
        - -framework AVFoundation
        - -framework AudioToolbox
        - -framework CoreAudio
        - -framework CoreFoundation
        - -framework Foundation
        - -framework UIKit
        - -lobjc
    dependencies:
      - target: #{pascal_name}AppleShellExtension
  #{pascal_name}AppleShellExtension:
    type: app-extension
    platform: iOS
    sources:
      - path: ../apple/generated/WidgetKit
      - path: ../apple/generated/ActivityKit
    settings:
      PRODUCT_BUNDLE_IDENTIFIER: #{@manifest.apple.bundle_identifier}.widgetkit
      INFOPLIST_FILE: ../apple/generated/WidgetKit/Info.plist
  #{pascal_name}UITests:
    type: bundle.ui-testing
    platform: iOS
    sources:
      - path: UITests
    dependencies:
      - target: #{pascal_name}
YML
    end

    private def widgets_catalog : UI::Widgets
      return UI::Widgets.new(@pascal_name, bundle_identifier: @manifest.apple.bundle_identifier) unless @manifest.apple.widgets.enabled
      @manifest.widgets_catalog(@pascal_name)
    end

    private def live_activities_catalog : UI::LiveActivities
      return UI::LiveActivities.new(@pascal_name, bundle_identifier: @manifest.apple.bundle_identifier) unless @manifest.apple.live_activities.enabled
      @manifest.live_activities_catalog(@pascal_name)
    end

    private def shortcuts_catalog : UI::AppShortcuts
      return UI::AppShortcuts.new(@pascal_name, bundle_identifier: @manifest.apple.bundle_identifier) unless @manifest.apple.shortcuts.enabled
      @manifest.shortcuts_catalog(@pascal_name)
    end

    private def notifications_catalog : UI::NotificationsCatalog
      return UI::NotificationsCatalog.new(@pascal_name, bundle_identifier: @manifest.apple.bundle_identifier) unless @manifest.apple.notifications.enabled
      @manifest.notifications_catalog(@pascal_name)
    end

    private def quick_actions_fragment : String
      catalog = if @manifest.apple.quick_actions.enabled
                  @manifest.quick_actions_catalog
                else
                  UI::QuickActionsCatalog.new
                end

      UI::HomeScreenQuickActions.export_plist_fragment(catalog)
    end

    private def ownership_readme : String
      <<-MARKDOWN
# Apple Shell Ownership

`mobile/apple/generated/**/*` is generator-owned output. Amber CLI can safely rewrite it from `config/native.yml`.

Keep hand edits in:

- `config/native.yml`
- `mobile/ios/Sources/**/*`

The generated directories currently cover:

- WidgetKit extension scaffolds
- ActivityKit attribute exports and wrapper widgets
- AppIntents scaffolds and shortcut providers
- notification registration scaffolds
- Home Screen quick action plist fragments
MARKDOWN
    end

    private def widget_bundle_wrapper : String
      widget_entries = widgets_catalog.widgets.map(&.widgetkit_struct_name)
      activity_entries = live_activities_catalog.activities.map { |activity| activity_widget_name(activity) }
      all_entries = widget_entries + activity_entries

      String.build do |io|
        io << GENERATED_HEADER
        io << "import WidgetKit\n"
        io << "import SwiftUI\n\n"
        io << "@main\n"
        io << "struct #{pascal_name}WidgetBundle: WidgetBundle {\n"
        io << "    @WidgetBundleBuilder\n"
        io << "    var body: some Widget {\n"

        if all_entries.empty?
          io << "        #{pascal_name}PlaceholderWidget()\n"
        else
          all_entries.each do |entry|
            io << "        #{entry}()\n"
          end
        end

        io << "    }\n"
        io << "}\n\n"

        if all_entries.empty?
          io << "struct #{pascal_name}PlaceholderWidget: Widget {\n"
          io << "    var body: some WidgetConfiguration {\n"
          io << "        StaticConfiguration(kind: \"#{app_name}-placeholder\", provider: PlaceholderProvider()) { entry in\n"
          io << "            Text(entry.title)\n"
          io << "        }\n"
          io << "        .configurationDisplayName(\"#{pascal_name}\")\n"
          io << "        .description(\"Enable widgets or live activities in config/native.yml to replace this placeholder.\")\n"
          io << "        .supportedFamilies([.systemSmall])\n"
          io << "    }\n"
          io << "}\n\n"
          io << "struct PlaceholderEntry: TimelineEntry {\n"
          io << "    let date: Date\n"
          io << "    let title: String\n"
          io << "}\n\n"
          io << "struct PlaceholderProvider: TimelineProvider {\n"
          io << "    func placeholder(in context: Context) -> PlaceholderEntry {\n"
          io << "        PlaceholderEntry(date: Date(), title: \"#{pascal_name}\")\n"
          io << "    }\n\n"
          io << "    func getSnapshot(in context: Context, completion: @escaping (PlaceholderEntry) -> Void) {\n"
          io << "        completion(PlaceholderEntry(date: Date(), title: \"#{pascal_name}\"))\n"
          io << "    }\n\n"
          io << "    func getTimeline(in context: Context, completion: @escaping (Timeline<PlaceholderEntry>) -> Void) {\n"
          io << "        completion(Timeline(entries: [PlaceholderEntry(date: Date(), title: \"#{pascal_name}\")], policy: .atEnd))\n"
          io << "    }\n"
          io << "}\n"
        end
      end
    end

    private def live_activity_widget_wrapper : String
      activities = live_activities_catalog.activities

      String.build do |io|
        io << GENERATED_HEADER
        io << "import ActivityKit\n"
        io << "import WidgetKit\n"
        io << "import SwiftUI\n\n"

        if activities.empty?
          io << "// Live activities are disabled in config/native.yml.\n"
        else
          activities.each do |activity|
            io << "struct #{activity_widget_name(activity)}: Widget {\n"
            io << "    var body: some WidgetConfiguration {\n"
            io << "        ActivityConfiguration(for: #{live_activities_enum_name}.#{activity_attributes_type(activity)}.self) { _ in\n"
            io << "            VStack(alignment: .leading, spacing: 8) {\n"
            io << "                Text(\"#{pascal_name}\")\n"
            io << "                    .font(.headline)\n"
            io << "                Text(\"#{activity.identifier}\")\n"
            io << "                    .font(.caption)\n"
            io << "                    .foregroundStyle(.secondary)\n"
            io << "            }\n"
            io << "            .padding(12)\n"
            io << "        } dynamicIsland: { _ in\n"
            io << "            DynamicIsland {\n"
            io << "                DynamicIslandExpandedRegion(.center) {\n"
            io << "                    Text(\"#{pascal_name}\")\n"
            io << "                }\n"
            io << "            } compactLeading: {\n"
            io << "                Text(\"#{abbreviated_app_name}\")\n"
            io << "            } compactTrailing: {\n"
            io << "                Text(\"Live\")\n"
            io << "            } minimal: {\n"
            io << "                Text(\"•\")\n"
            io << "            }\n"
            io << "        }\n"
            io << "    }\n"
            io << "}\n\n"
          end
        end
      end
    end

    private def app_shortcuts_provider : String
      shortcuts = shortcuts_catalog.shortcuts

      String.build do |io|
        io << GENERATED_HEADER
        io << "import AppIntents\n\n"
        io << "struct #{pascal_name}AppShortcutsProvider: AppShortcutsProvider {\n"
        io << "    static var appShortcuts: [AppShortcut] {\n"

        shortcuts.each do |shortcut|
          phrases = normalized_shortcut_phrases(shortcut)
          io << "            AppShortcut(\n"
          io << "                intent: #{shortcut.app_intent_struct_name}(),\n"
          io << "                phrases: [#{phrases.map { |phrase| swift_app_shortcut_phrase_literal(phrase) }.join(", ")}],\n"
          io << "                shortTitle: #{Naming.swift_string_literal(shortcut.title)},\n"
          io << "                systemImageName: #{Naming.swift_string_literal(shortcut.icon || "app")}\n"
          io << "            )\n"
        end

        io << "    }\n"
        io << "}\n"
      end
    end

    private def normalized_shortcut_phrases(shortcut) : Array(String)
      phrases = shortcut.phrases.empty? ? ["Open #{pascal_name}"] : shortcut.phrases
      phrases.map { |phrase| normalize_shortcut_phrase(phrase) }
    end

    private def normalize_shortcut_phrase(phrase : String) : String
      normalized = phrase
        .gsub("\\(.applicationName)", APP_SHORTCUT_APP_NAME_PLACEHOLDER)
        .gsub("${applicationName}", APP_SHORTCUT_APP_NAME_PLACEHOLDER)

      app_shortcut_application_name_variants.each do |variant|
        normalized = normalized.gsub(variant, APP_SHORTCUT_APP_NAME_PLACEHOLDER)
      end

      unless normalized.includes?(APP_SHORTCUT_APP_NAME_PLACEHOLDER)
        normalized = "#{normalized} in #{APP_SHORTCUT_APP_NAME_PLACEHOLDER}"
      end

      normalized
    end

    private def app_shortcut_application_name_variants : Array(String)
      [
        pascal_name,
        app_name,
        app_name.gsub(/[_-]+/, " "),
        app_name.gsub('_', '-'),
      ].uniq.reject(&.empty?).sort_by { |value| -value.size }
    end

    private def swift_app_shortcut_phrase_literal(value : String) : String
      escaped = value
        .gsub("\\", "\\\\")
        .gsub("\"", "\\\"")
        .gsub("\n", "\\n")
        .gsub(APP_SHORTCUT_APP_NAME_PLACEHOLDER, "\\(.applicationName)")

      %("#{escaped}")
    end

    private def notifications_bootstrap : String
      String.build do |io|
        io << GENERATED_HEADER
        io << "import Foundation\n"
        io << "import UserNotifications\n\n"
        io << "enum #{pascal_name}NotificationsBootstrap {\n"
        io << "    static func registerCategories() {\n"
        io << "        #{notifications_enum_name}.register()\n"
        io << "    }\n"
        io << "}\n"
      end
    end

    private def ios_app_source : String
      <<-SWIFT
import SwiftUI

@main
struct #{pascal_name}App: App {
    @UIApplicationDelegateAdaptor(#{pascal_name}AppDelegate.self) private var appDelegate

    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}
SWIFT
    end

    private def ios_app_delegate_source : String
      <<-SWIFT
import UIKit

final class #{pascal_name}AppDelegate: NSObject, UIApplicationDelegate {
    func application(
        _ application: UIApplication,
        didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil
    ) -> Bool {
        #{pascal_name}NotificationsBootstrap.registerCategories()
        return true
    }
}
SWIFT
    end

    private def ios_content_view_source : String
      <<-SWIFT
import SwiftUI

struct ContentView: View {
    var body: some View {
        VStack(spacing: 16) {
            Text("#{pascal_name}")
                .font(.title2)
                .fontWeight(.semibold)
            Text("Amber native Apple host scaffold")
                .foregroundStyle(.secondary)
        }
        .padding(24)
    }
}
SWIFT
    end

    private def widget_extension_info_plist : String
      <<-PLIST
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleIdentifier</key>
  <string>$(PRODUCT_BUNDLE_IDENTIFIER)</string>
  <key>CFBundleDisplayName</key>
  <string>#{pascal_name} Shell</string>
  <key>NSExtension</key>
  <dict>
    <key>NSExtensionPointIdentifier</key>
    <string>com.apple.widgetkit-extension</string>
  </dict>
</dict>
</plist>
PLIST
    end

    private def notifications_enum_name : String
      Naming.swift_module_name(@pascal_name, "Notifications")
    end

    private def live_activities_enum_name : String
      Naming.swift_module_name(@pascal_name, "LiveActivities")
    end

    private def activity_widget_name(activity : UI::LiveActivity) : String
      "#{Naming.pascalize(activity.identifier, "LiveActivity")}LiveActivityWidget"
    end

    private def activity_attributes_type(activity : UI::LiveActivity) : String
      Naming.pascalize(activity.attributes_type, "LiveActivity")
    end

    private def abbreviated_app_name : String
      short = @pascal_name.size > 4 ? @pascal_name[0, 4] : @pascal_name
      short.empty? ? "App" : short
    end

    private def write_file(project_path : String, relative_path : String, content : String) : Nil
      absolute_path = File.join(project_path, relative_path)
      Dir.mkdir_p(File.dirname(absolute_path))
      File.write(absolute_path, content)
    end
  end
end
